---
title: "PROSAIL"
author: "Zhehan"
date: "February 7, 2020"
output: html_document
---

#Packages
```{r}
library(hsdar)
```

#Variable range
```{r}
N_range = c(1,2)
Cab_range = c(20, 70)
Cm_range = c(0.004, 0.007)
Cw_range = c(0.05, 0.03)
LAI_range = c(0.001, 6)
ALA_range = c(30, 60)
hspot_range = c(0.05, 1)
SB_range = c(0.05, 1)

n = 100
paras <- data.frame("N" = min(N_range)+(max(N_range) - min(N_range))*runif(n),
                    "Cab" = min(Cab_range)+(max(Cab_range) - min(Cab_range))*runif(n),
                    "Cm" = min(Cm_range)+(max(Cm_range) - min(Cm_range))*runif(n),
                    "Cw" = min(Cw_range)+(max(Cw_range) - min(Cw_range))*runif(n),
                    "LAI" = min(LAI_range)+(max(LAI_range) - min(LAI_range))*runif(n),
                    "hspot" = min(hspot_range)+(max(hspot_range) - min(hspot_range))*runif(n))

```

#Cost function
```{r}
cost_rmse <- function(nd, nb, Rm, Rs){
  #nd is the number of viewing direction
  #nb is the number of bands
  #Rm is the measured reflectance
  #Rs is the simulated reflectance
  for(i in 1:nd){
    for(j in 1:nb){
      Rm[[i]]
    }
  }
  return(xrmse)
}
```

#Sample prosail run
```{r}
spectrum <- PROSAIL(N = 1.3)
plot(spectrum)

spectra <- PROSAIL(parameterList = paras)
plot(spectra, col = "red")
plot(subset(spectra, LAI>2 & LAI <4))

df_micasense <- data.frame("center" = c(475, 560, 668, 717, 842), "fwhm" = c(32, 27, 16, 12, 57))
spectra_micasense <- spectralResampling(spectra, df_micasense)
plot(spectra_micasense, type = "b", main = "Micasense Rededge")


spectra_resampled <- spectralResampling(spectra, 13)
```

#Spectral unmixing
```{r}
av1 <- USGS_get_available_files()
soil_spectra <- USGS_retrieve_files(avl = av1, pattern = "grass-fescue")
soil_spectra_resampole <- spectralResampling(soil_spectra[1,], "Sentinel-2")

```

